site_name: The RBA Community
site_description: >-
  The RBA Community is a group of professionals dedicated to advancing the field of risk-based alerting (RBA) and Splunk Enterprise Security (ES). Our mission is to provide a forum for sharing knowledge, best practices, and the latest developments in RBA and ES, and to help professionals enhance their understanding and skills in these areas.
# edit_uri: ""
# repo_url: https://github.com/ZachChristensen28/rba-community
# repo_name: ZachChristensen28/rba-community

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  # - search
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/rba_community_small.png
  favicon: assets/rba_community_small.png
  features:
    - content.code.copy
    # - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: rba-light
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/12702283/
      name: RBA Community LinkedIn Group
    - icon: fontawesome/brands/github
      link: https://splunk.github.io/rba/
      name: RBA Community GitHub
    - icon: fontawesome/brands/slack
      link: https://outpost-security.com/slack/
      name: RBA Community Slack

nav:
  - Home: index.md
