site_name: The RBA Community
site_description: >-
  The RBA Community is a group of professionals dedicated to advancing the field of risk-based alerting (RBA) and Splunk Enterprise Security (ES). Our mission is to provide a forum for sharing knowledge, best practices, and the latest developments in RBA and ES, and to help professionals enhance their understanding and skills in these areas.

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - no-zoom
      auto_caption: true
      caption_position: bottom
  - search
  - minify:
      minify_html: true
  - tags:
      tags_file: apps/tags.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  logo: assets/rba_logo_small.png
  favicon: assets/favicon-32x32.png
  features:
    - announce.dismiss
    - content.code.copy
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: rba-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: material/google-drive
      link: https://drive.google.com/drive/folders/1t514OI5obxInEmM8PzQZz-JIgcL2LE9G
      name: The RBA Community Google Drive
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/12702283/
      name: The RBA Community LinkedIn Group
    - icon: fontawesome/brands/github
      link: https://splunk.github.io/rba/
      name: The RBA Community GitHub
    - icon: fontawesome/brands/slack
      link: https://outpost-security.com/slack/
      name: The RBA Community Slack
  analytics:
    provider: google
    property: G-NE2FQCZZ3E

copyright: >
  Copyright &copy; 2023 The RBA Community

nav:
  - Home: index.md
  - The Risky Times: risky-times/index.md
  - Video Library: library/index.md
  - Community Involvment: 
      - Contributing: community/contribute.md
      - RBA Champions: community/rba-champions.md
  - Partner Support:
      - partners/index.md
      - Outpost Security: partners/outpost.md
      - SP6: partners/sp6.md
      - Alchemy Global Networks: partners/alchemy.md
      - Support The RBA Community: 
          - partners/support/index.md
  - RBA Apps:
      - apps/index.md
      - Featured Apps:
          - Assets & Identities: 
            - SA-admon: apps/asset-identity/sa-admon.md
            # - SA-AwsAssets: apps/asset-identity/sa-awsassets.md
            - SA-CrowdstrikeDevices: apps/asset-identity/sa-crowdstrikedevices.md
            # - SA-CrowdStrikeIdentites: apps/asset-identity/sa-crowdstrikeidentities.md
            # - SA-Rapid7Assets: apps/asset-identity/sa-rapid7assets.md
            # - SA-SentinelOneDevices: apps/asset-identity/sa-sentineloneassets.md
          - Health:
            - Broken Hosts: apps/health/broken-hosts.md
            - Data Model Mechanic: apps/health/data-model-mechanic.md
            - TrackMe: apps/health/trackme.md
          - Implement:
            - Anomaly Detection: apps/implement/anomaly-detection.md
            - Behavioral Profiling: apps/implement/behavioral-profiling.md
            - Detection Insights: apps/implement/detection-insights.md
            - Fraud Analytics: apps/implement/fraud-analytics.md
            - RBA Navigator: apps/implement/rba-navigator.md
            - Tuning Framework: apps/implement/tuning-framework.md
            - Zero-To-One: apps/implement/zero-to-one.md
          - Learn:
            - threat_object_fun: apps/learn/threat_object_fun.md
          - Manage:
            - ES Config Explorer: apps/manage/es-config-explorer.md
            - ES Choreographer: apps/manage/es-choreographer.md
            - Conf Manager: apps/manage/conf-manager.md
          - Misc Content:
            - Correlation Rules Runner: apps/misc/correlation-rules-runner.md 
            - GV-Utils: apps/misc/gv-utils.md
            - RBA GitHub: apps/misc/rba-github.md
          - Visualizations:
            - Link Analysis: apps/visualizations/link-analysis.md
      - Submit an App:
        - apps/submit/index.md
  - Detection As Code: dac/index.md