site_name: The RBA Community
site_description: >-
  The RBA Community is a group of professionals dedicated to advancing the field of risk-based alerting (RBA) and Splunk Enterprise Security (ES). Our mission is to provide a forum for sharing knowledge, best practices, and the latest developments in RBA and ES, and to help professionals enhance their understanding and skills in these areas.
# edit_uri: ""
# repo_url: https://github.com/ZachChristensen28/rba-community
# repo_name: ZachChristensen28/rba-community
#

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - no-zoom
      auto_caption: true
      caption_position: bottom
  # - search
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  logo: assets/rba_community_small.png
  favicon: assets/rba_community_small.png
  features:
    - announce.dismiss
    - content.code.copy
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: rba-light
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: indigo
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
      - manage
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-NE2FQCZZ3E
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/12702283/
      name: RBA Community LinkedIn Group
    - icon: fontawesome/brands/github
      link: https://splunk.github.io/rba/
      name: RBA Community GitHub
    - icon: fontawesome/brands/slack
      link: https://outpost-security.com/slack/
      name: RBA Community Slack

copyright: >
  Copyright &copy; 2023 The RBA Community –
  <a href="#__consent">Change cookie settings</a>

nav:
  - Home: index.md
  - The Risky Times: risky-times/index.md
  - "\"The Office\" Hour Recordings": office-hours/index.md
  - Contribute to The RBA Community: contribute/index.md
