site_name: RBA Community
# edit_uri: ""
# repo_url: https://github.com/ZachChristensen28/rba-community
# repo_name: ZachChristensen28/rba-community

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  # - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/rba_community.png
  favicon: assets/rba_community.png
  features:
    # - header.autohide
    # - navigation.indexes
    # - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    # - navigation.top
    # - toc.integrate
    # - toc.follow
    # - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
